### ISSUE TITLE
[Wiki] Configuring desktop environments

### ISSUE THREAD

**Issue by Kabouik** [sailfish-containers/harbour-containers#10]
**Probably low priority**

Wiki entries with some basic guidelines on how to set up `xfce4`, `i3`, `i3-gaps` and other DEs and WMs could be useful. I reckon a good fraction of new users would be pretty excited about LXC and install it on their phone, then be overwhelmed and give up before their containers are actually well configured to be easily used on mobile. Either because configuring an OS is time consuming, let alone on a mobile device that requires some specific tricks they might not know about, or because at first a desktop OS on small screen with no adequate controls or DPI could appear as a bad idea. Yet we know it's not cumbersome to use once configured (at least on Pro¹).

Messy and non-exhaustive list of things that could be mentioned:
- xfce4
- i3 and variants
- DPI, UI scaling, font size
- touch scrolling in Firefox
- right click emulation (I don't have much knowledge on that but I noticed not all applications emulate it the same way: some use long press, some use `Shift` + tap, some just have no support for touch right clicks; this could be mentioned)
- Onboard
- option to enable mouse (add `-plugin evdevmouse` to `LIPSTICK_OPTIONS:` in `/var/lib/environment/compositor/droid-hal-device.conf`); no visible cursor for now
- landscape versus portrait uses and implications for Onboard
- possibly provide some default configuration files for Onboard and xfce4 to automatically install with `dconf` during X setup; there should be a security if the setup button is pressed when configuration files already exist: either abort, or ask for confirmation to reset to default
- maybe a mention of the importance of setting keybindings, even for xfce4, and even for touch-only devices, because accurately tapping or moving windows on a capacitive screen is not fun at all; possibly list some suggestions for xfce4 (might not be necessary for i3, it's implied): move window, maximize, tile, minimize, resize, switch tabs in browser…
- perhaps a bit off-topic: indicating what file to edit to add mount points, namely mount `/home/nemo` either as an additional mount, or merge it with `/merge/user`

Wiki entries shouldn't be too verbose though. Exactly the opposite of this message. We know nobody reads wikis. But pictures and some guidelines on which files to edit on the first run, possibly from `lxc-attach` until the DPI is adjusted, would be cool. Scripts for "sane mobile default configurations" too.

Answering @edp17's comment in another issue:

> @Kabouik : Yeah, some settings are not easy to set in the xfce4. Especially when a dropdown is involved. When I tap on it, the dropdown opens but immediately closes before I can select any options. (This is not limited to the onboard setup but for anything else e.g. setting the tree pane icon size of File Manager is a mission impossible task. :)

I don't currently have a container running xfce4 but I don't remember that, and I don't think I had that in `sailfish_ubu_chroot` (maybe check [this](https://www.youtube.com/watch?v=DLl92bISgAo) in case you observe the same issue and I just didn't notice it in real use). I do observe, however, Firefox context menu being a bit difficult sometimes. But not all the time, and when this happens, just keeping my finger on the screen and sliding it to select the menu entry I want works. Can you try that in the file manager too?

**Comment by edp17** [comment]
Yes, I tried to scroll down with keeping my finger on, but that didn't help either. It just did not select the option I wanted. However, I found a workaround. I tap on the dropdown (it opens and closes but doesn't matter) then in Onboard I use the down/up arrows to select the wanted option. Fortunately, this works. :)

**Comment by edp17** [comment]
Regarding the mouse cursor issue, I have found [this](http://talk.maemo.org/showthread.php?t=15111) topic. I have tried the compiled version, but seemingly it needs to be recompiled under sailfish. (Or might this won't work at all.)

**Comment by edp17** [comment]
Nope, that app doesn't run. :(

**Comment by Kabouik** [comment]
Ok. You can try the following, it works on Pro¹. 

```
nano var/lib/environment/compositor/droid-hal-device.conf
```

And add ` -plugin evdevmouse` at the end of the `LIPSTICK_OPTIONS:` line. 

This enables the mouse in the all LXC apps, and even in some native apps (sometimes only in some screens of the apps). However there are still some quirks to fix: the cursor is not visible, and the mouse behaves as if the phone was in portrait, even if it is in landscape.

**Comment by edp17** [comment]
Yeah, I have added that plugin into the config but without seeing the cursor, it is not really usable. Clicks do work, but I don't really see where I click on. :)

**Comment by Kabouik** [comment]
Absolutely, it's unusable right now. I've tried adding icon themes in SFOS but no luck so far.

Rotation is also an issue, as xinput doesn't seem to be able to change settings for virtual devices in xwayland, and libinput, the Wayland alternative, could only rotate trackpoints even if we could compile it for SFOS. I wonder if landscape rotation for the pointer this could be hardcoded in the compositor, since there is not much point in using a USB mouse in portrait anyway.

**Comment by Kabouik** [comment]
Note that I forgot to post it here, but the cursor is now fully useable thanks to @elros34. Still a little hacky, but if you're there wanting a cursor in your LXC container, you may not mind the couple extra steps: https://github.com/sailfish-on-fxtecpro1/droid-config-t5/issues/41#issuecomment-679148396

**Comment by vaskas** [comment]
Speaking as a first time user, I've just spent ~3 hours setting up a Debian GUI container with XFCE4 on a non-keyboard device (XZ2). These were the biggest pain points (in the order of magnitude haha):

1. Realising I needed to run 2 terminals, one for `qxdisplay`, the other one for `start_desktop.sh` - in addition to running the Containers app. This is really clunky and I wish the Containers app did all that. The `X session` button does nothing for me.
2. Configuring XFCE4 and onboard to behave in a more touch-friendly way, e.g.
  * Onboard to have bigger buttons and appear automatically when an input field is focused
  * XFCE4 to have a bigger DPI
  * Thunar to accept single clicks to navigate directories
3. Having to figure out which was the best supported distro. That said, I knew from Kabouik's brilliant videos that it had to be Debian. If I didn't watch them I would go with Arch and waste time. 
4. Having to install packages by hand to install harbour-containers and its dependencies.

These were the things I really liked:
1. The container creation experience. Very smooth even with the terminal popping up at a certain time.
2. The button to install the X session dependencies
3. The existence of this awesome project!

I don't believe in Wiki articles (the docs always rot) and IMHO the best approach would be to create one dead-simple preset for touch devices, and another one for the keyboard ones. Then the power users can customise them further, or keep them as they are.

**Comment by edp17** [comment]
> Speaking as a first time user, I've just spent ~3 hours setting up a Debian GUI container with XFCE4 on a non-keyboard device (XZ2). These were the biggest pain points (in the order of magnitude haha):

Well done! :) To save a little time, you should have read the instruction here: https://talk.maemo.org/showthread.php?t=101080
You don't need 2 terminals if you use the script that I wrote. (Basically, you don't need terminal at all if you run the script with Shellex)

**Comment by Kabouik** [comment]
> **Probably low priority**
> 
> Wiki entries with some basic guidelines on how to set up `xfce4`, `i3`, `i3-gaps` and other DEs and WMs could be useful. I reckon a good fraction of new users would be pretty excited about LXC and install it on their phone, then be overwhelmed and give up before their containers are actually well configured to be easily used on mobile. Either because configuring an OS is time consuming, let alone on a mobile device that requires some specific tricks they might not know about, or because at first a desktop OS on small screen with no adequate controls or DPI could appear as a bad idea. Yet we know it's not cumbersome to use once configured (at least on Pro¹).
> 
> Messy and non-exhaustive list of things that could be mentioned:
> 
> * xfce4
> * i3 and variants
> * DPI, UI scaling, font size
> * touch scrolling in Firefox
> * right click emulation (I don't have much knowledge on that but I noticed not all applications emulate it the same way: some use long press, some use `Shift` + tap, some just have no support for touch right clicks; this could be mentioned)
> * Onboard
> * option to enable mouse (add `-plugin evdevmouse` to `LIPSTICK_OPTIONS:` in `/var/lib/environment/compositor/droid-hal-device.conf`); no visible cursor for now
> * landscape versus portrait uses and implications for Onboard
> * possibly provide some default configuration files for Onboard and xfce4 to automatically install with `dconf` during X setup; there should be a security if the setup button is pressed when configuration files already exist: either abort, or ask for confirmation to reset to default
> * maybe a mention of the importance of setting keybindings, even for xfce4, and even for touch-only devices, because accurately tapping or moving windows on a capacitive screen is not fun at all; possibly list some suggestions for xfce4 (might not be necessary for i3, it's implied): move window, maximize, tile, minimize, resize, switch tabs in browser…
> * perhaps a bit off-topic: indicating what file to edit to add mount points, namely mount `/home/nemo` either as an additional mount, or merge it with `/merge/user`
> 
> Wiki entries shouldn't be too verbose though. Exactly the opposite of this message. We know nobody reads wikis. But pictures and some guidelines on which files to edit on the first run, possibly from `lxc-attach` until the DPI is adjusted, would be cool. Scripts for "sane mobile default configurations" too.
> 
> Answering @edp17's comment in another issue:
> 
> > @Kabouik : Yeah, some settings are not easy to set in the xfce4. Especially when a dropdown is involved. When I tap on it, the dropdown opens but immediately closes before I can select any options. (This is not limited to the onboard setup but for anything else e.g. setting the tree pane icon size of File Manager is a mission impossible task. :)
> 
> I don't currently have a container running xfce4 but I don't remember that, and I don't think I had that in `sailfish_ubu_chroot` (maybe check [this](https://www.youtube.com/watch?v=DLl92bISgAo) in case you observe the same issue and I just didn't notice it in real use). I do observe, however, Firefox context menu being a bit difficult sometimes. But not all the time, and when this happens, just keeping my finger on the screen and sliding it to select the menu entry I want works. Can you try that in the file manager too?



> Speaking as a first time user, I've just spent ~3 hours setting up a Debian GUI container with XFCE4 on a non-keyboard device (XZ2). These were the biggest pain points (in the order of magnitude haha):
> 
> 1. Realising I needed to run 2 terminals, one for `qxdisplay`, the other one for `start_desktop.sh` - in addition to running the Containers app. This is really clunky and I wish the Containers app did all that. The `X session` button does nothing for me.
> 2. Configuring XFCE4 and onboard to behave in a more touch-friendly way, e.g.
> 
> * Onboard to have bigger buttons and appear automatically when an input field is focused
> * XFCE4 to have a bigger DPI
> * Thunar to accept single clicks to navigate directories
> 
> 3. Having to figure out which was the best supported distro. That said, I knew from Kabouik's brilliant videos that it had to be Debian. If I didn't watch them I would go with Arch and waste time.
> 4. Having to install packages by hand to install harbour-containers and its dependencies.
> 
> These were the things I really liked:
> 
> 1. The container creation experience. Very smooth even with the terminal popping up at a certain time.
> 2. The button to install the X session dependencies
> 3. The existence of this awesome project!
> 
> I don't believe in Wiki articles (the docs always rot) and IMHO the best approach would be to create one dead-simple preset for touch devices, and another one for the keyboard ones. Then the power users can customise them further, or keep them as they are.

More documentation in the wiki would still be welcome, but `harbour-containers` 0.8 should make it less critical since we now have:
- README stating clearly which distributions are supported
- Easy installation from Chum GUI
- Usable default configurations for Onboard, as well as both Xfce4 (scaling, single clicks to navigate directories) and i3 (keybndings (see `Alt`+`h`), i3bar, terminal), with a new option to install i3 at container creation
- Touch scrolling by default in Firefox
- Dynamic orientation (for SFOS ≥ 4.2, the old selector in container settings is still available for SFOS < 4.2)
- Good base keybindings for i3 to make it usable without `ssh`
- Optional mount entry in container configurations `/var/lib/lxc/<containername>/config` to uncomment if SFOS's home folder is to be shown in LXC
- Right click emulation on long tap (finicky, and only in Arch)
