### ISSUE TITLE
Android containers

### ISSUE THREAD

**Issue by Kabouik** [sailfish-containers/harbour-containers#16]
Some devices can run Alien Dalvik, but there are some limitations such as no Bluetooth or no camera, and not all devices have an AD version. I believe @0312birdzhang has been working on porting Anbox to SailfishOS because I saw some rpms on OBS, but as far as I understand it is not working yet.

I was stumbling upon this article: https://stgraber.org/2013/12/23/lxc-1-0-some-more-advanced-container-usage/

This looks interesting, Would the part on "Android containers" work with `sailfish-containers`? @0312birdzhang, what do you think? 

I pasted the corresponding section below:

---

# Android containers

I’ve often been asked whether it was possible to run Android in an LXC container. Well, the short answer is yes. However it’s not very simple and it really depends on what you want to do with it.

The first thing you’ll need if you want to do this is get your machine to run an Android kernel, you’ll need to have any modules needed by Android built and loaded before you can start the container.

Once you have that, you’ll need to create a new container by hand.
Let’s put it in `/var/lib/lxc/android/`, in there, you need a configuration file similar to this one:

``` bash
lxc.rootfs = /var/lib/lxc/android/rootfs
lxc.utsname = armhf

lxc.network.type = none

lxc.devttydir = lxc
lxc.tty = 4
lxc.pts = 1024
lxc.arch = armhf
lxc.cap.drop = mac_admin mac_override
lxc.pivotdir = lxc_putold

lxc.hook.pre-start = /var/lib/lxc/android/pre-start.sh

lxc.aa_profile = unconfined
```

`/var/lib/lxc/android/pre-start.sh` is where the interesting bits happen. It needs to be an executable shell script, containing something along the lines of:

```bash
#!/bin/sh
mkdir -p $LXC_ROOTFS_PATH
mount -n -t tmpfs tmpfs $LXC_ROOTFS_PATH

cd $LXC_ROOTFS_PATH
cat /var/lib/lxc/android/initrd.gz | gzip -d | cpio -i

# Create /dev/pts if missing
mkdir -p $LXC_ROOTFS_PATH/dev/pts
```

Then get the initrd for your device and place it in `/var/lib/lxc/android/initrd.gz`.

At that point, when starting the LXC container, the Android initrd will be unpacked on a tmpfs (similar to Android’s ramfs) and Android’s init will be started which in turn should mount any partition that Android requires and then start all of the usual services.

Because there are no `apparmor`, `cgroup` or even network configuration applied to it, the container will have a lot of rights and will typically completely crash the machine. You unfortunately have to be familiar with the way Android works and not be afraid to modify its init scripts if not even its init process to only start the bits you actually want.

I can’t provide a generic recipe there as it completely depends on what you’re interested on, what version of Android and what device you’re using. But it’s clearly possible to do and you may want to look at Ubuntu Touch to see how we’re doing it by default there.

One last note, Android’s init script isn’t in `/sbin/init`, so you need to tell LXC where to load it with:

```
lxc-start -n android -- /init
```

**Comment by 0312birdzhang** [comment]
Yeah, i was working on porting Anbox to SailfishOS, it's out of my skill now. 
Anbox uses lxc  run android container as you mentioned.

**Comment by Kabouik** [comment]
I think Waydroid now covers this case nicely, with a pretty large community.
