### ISSUE TITLE
Error after deleting a container

### ISSUE THREAD

**Issue by JacekJagosz** [sailfish-containers/harbour-containers#27]
I installed the 0.6 version from Chum on Xperia 10 III (aarch64).
I launched it, created new Debian container that was supposed to have a GUI. It got stuck at "starting setup" so I left it overnight, in the morning it still said the same thing. So I deleted the cobtainer, it didn't disappear, so I deleted it again. When I launched the app again it showed an empty screen, with no container or option to add the new one.
If I launch it from the terminal I am getting
```bash
[W] unknown:12 - file:///usr/share/harbour-containers/qml/harbour-containers.qml:12:5: QML Daemon: QDBusError("org.freedeskto
p.DBus.Python.subprocess.CalledProcessError", "Traceback (most recent call last):\n  File \"/usr/lib64/python3.8/site-package
s/dbus/service.py\", line 711, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\n  File \"/usr/share/ha
rbour-containers/service/daemon.py\", line 477, in get_containers\n    self._refresh()\n  File \"/usr/share/harbour-container
s/service/daemon.py\", line 115, in _refresh\n    self.containers = lxc.get_containers()\n  File \"/usr/share/harbour-contain
ers/service/libs/lxc.py\", line 41, in get_containers\n    cmd_out = subprocess.check_output(['lxc-info', '-n', container,'-p
','-s','-S']).decode().split(\"\\n\")\n  File \"/usr/lib64/python3.8/subprocess.py\", line 415, in check_output\n    return r
un(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib64/python3.8/subprocess.py\", line 516, in run\n
raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['lxc-info', '-n', 'Debian', '-p',
'-s', '-S']' returned non-zero exit status 1.\n")
[W] unknown:12 - file:///usr/share/harbour-containers/qml/harbour-containers.qml:12:5: QML Daemon: QDBusError("org.freedeskto
p.DBus.Python.subprocess.CalledProcessError", "Traceback (most recent call last):\n  File \"/usr/lib64/python3.8/site-package
s/dbus/service.py\", line 711, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\n  File \"/usr/share/ha
rbour-containers/service/daemon.py\", line 477, in get_containers\n    self._refresh()\n  File \"/usr/share/harbour-container
s/service/daemon.py\", line 115, in _refresh\n    self.containers = lxc.get_containers()\n  File \"/usr/share/harbour-contain
ers/service/libs/lxc.py\", line 41, in get_containers\n    cmd_out = subprocess.check_output(['lxc-info', '-n', container,'-p
','-s','-S']).decode().split(\"\\n\")\n  File \"/usr/lib64/python3.8/subprocess.py\", line 415, in check_output\n    return r
un(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib64/python3.8/subprocess.py\", line 516, in run\n
raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['lxc-info', '-n', 'Debian', '-p',
'-s', '-S']' returned non-zero exit status 1.\n")
[W] unknown:12 - file:///usr/share/harbour-containers/qml/harbour-containers.qml:12:5: QML Daemon: QDBusError("org.freedeskto
p.DBus.Python.subprocess.CalledProcessError", "Traceback (most recent call last):\n  File \"/usr/lib64/python3.8/site-package
s/dbus/service.py\", line 711, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\n  File \"/usr/share/ha
rbour-containers/service/daemon.py\", line 477, in get_containers\n    self._refresh()\n  File \"/usr/share/harbour-container
s/service/daemon.py\", line 115, in _refresh\n    self.containers = lxc.get_containers()\n  File \"/usr/share/harbour-contain
ers/service/libs/lxc.py\", line 41, in get_containers\n    cmd_out = subprocess.check_output(['lxc-info', '-n', container,'-p
','-s','-S']).decode().split(\"\\n\")\n  File \"/usr/lib64/python3.8/subprocess.py\", line 415, in check_output\n    return r
un(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib64/python3.8/subprocess.py\", line 516, in run\n
raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['lxc-info', '-n', 'Debian', '-p',
'-s', '-S']' returned non-zero exit status 1.\n")
[W] unknown:12 - file:///usr/share/harbour-containers/qml/harbour-containers.qml:12:5: QML Daemon: QDBusError("org.freedeskto
p.DBus.Python.subprocess.CalledProcessError", "Traceback (most recent call last):\n  File \"/usr/lib64/python3.8/site-package
s/dbus/service.py\", line 711, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\n  File \"/usr/share/ha
rbour-containers/service/daemon.py\", line 477, in get_containers\n    self._refresh()\n  File \"/usr/share/harbour-container
s/service/daemon.py\", line 115, in _refresh\n    self.containers = lxc.get_containers()\n  File \"/usr/share/harbour-contain
ers/service/libs/lxc.py\", line 41, in get_containers\n    cmd_out = subprocess.check_output(['lxc-info', '-n', container,'-p
','-s','-S']).decode().split(\"\\n\")\n  File \"/usr/lib64/python3.8/subprocess.py\", line 415, in check_output\n    return r
un(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib64/python3.8/subprocess.py\", line 516, in run\n
raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['lxc-info', '-n', 'Debian', '-p',
'-s', '-S']' returned non-zero exit status 1.\n")
[W] unknown:12 - file:///usr/share/harbour-containers/qml/harbour-containers.qml:12:5: QML Daemon: QDBusError("org.freedeskto
p.DBus.Python.subprocess.CalledProcessError", "Traceback (most recent call last):\n  File \"/usr/lib64/python3.8/site-package
s/dbus/service.py\", line 711, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\n  File \"/usr/share/ha
rbour-containers/service/daemon.py\", line 477, in get_containers\n    self._refresh()\n  File \"/usr/share/harbour-container
s/service/daemon.py\", line 115, in _refresh\n    self.containers = lxc.get_containers()\n  File \"/usr/share/harbour-contain
ers/service/libs/lxc.py\", line 41, in get_containers\n    cmd_out = subprocess.check_output(['lxc-info', '-n', container,'-p
','-s','-S']).decode().split(\"\\n\")\n  File \"/usr/lib64/python3.8/subprocess.py\", line 415, in check_output\n    return r
un(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib64/python3.8/subprocess.py\", line 516, in run\n
raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['lxc-info', '-n', 'Debian', '-p',
'-s', '-S']' returned non-zero exit status 1.\n")
[W] unknown:12 - file:///usr/share/harbour-containers/qml/harbour-containers.qml:12:5: QML Daemon: QDBusError("org.freedeskto
p.DBus.Python.subprocess.CalledProcessError", "Traceback (most recent call last):\n  File \"/usr/lib64/python3.8/site-package
s/dbus/service.py\", line 711, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\n  File \"/usr/share/ha
rbour-containers/service/daemon.py\", line 477, in get_containers\n    self._refresh()\n  File \"/usr/share/harbour-container
s/service/daemon.py\", line 115, in _refresh\n    self.containers = lxc.get_containers()\n  File \"/usr/share/harbour-contain
ers/service/libs/lxc.py\", line 41, in get_containers\n    cmd_out = subprocess.check_output(['lxc-info', '-n', container,'-p
','-s','-S']).decode().split(\"\\n\")\n  File \"/usr/lib64/python3.8/subprocess.py\", line 415, in check_output\n    return r
un(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib64/python3.8/subprocess.py\", line 516, in run\n
raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['lxc-info', '-n', 'Debian', '-p',
'-s', '-S']' returned non-zero exit status 1.\n")
```
I guess there is something leftover from the debian container, how can I delete it?

**Comment by Kabouik** [comment]
/> I installed the 0.6 version from Chum on Xperia 10 III (aarch64).
What version of SFOS are you using and what is your SFOS username? Did you have an other version of `harbour-containers` installed previously, and if so, did you uninstall `harbour-containers`, `qxdisplay`, `qxcompositor`, `lxc-templates-desktop` first, and did you reboot to make sure the old daemon was not running anymore?

> I launched it, created new Debian container that was supposed to have a GUI. It got stuck at "starting setup" so I left it overnight, in the morning it still said the same thing.
Can you describe how it was "stuck"? The icon in `harbour-containers" was spinning but no terminal window was opened to ask you to type your container's user password?

> So I deleted the cobtainer, it didn't disappear, so I deleted it again. When I launched the app again it showed an empty screen, with no container or option to add the new one.
You deleted it using the GUI, or using the CLI? In the latter case, did you use `devel-su lxc-destroy -n <container-name>` or did you `rm`some folders (if so, which ones)? You may want try uninstalling  `harbour-containers`, `qxdisplay`, `qxcompositor`, `lxc-templates-desktop` from command line, rebooting, and reinstalling `harbour-containers` from Chum. Let us know, it think it could be due to installing the new `harbour-containers` while the old daemon was still running, and in that case I need to update the instructions.

> If I launch it from the terminal I am getting
Can you share the command that you use to launch it?

**Comment by JacekJagosz** [comment]
I am on freshly installed 4.4.0.68, never used containers before, reinstalled it,I rebooted, same thing.
Because it is a new install my user is called defaultuser and for launching it I simply used `harbour-containers`.
The app seemed to work just fine untill it stuck on setup, and broke when I deleted that container mid-setup.
I only launched it from terminal once I needed debug output to know why it broke.

**Comment by Kabouik** [comment]
Did you check that your device meets the kernel requirements](https://github.com/sailfish-containers/lxc-templates-desktop/wiki/Requirements)?

**Comment by JacekJagosz** [comment]
Yes, my kernel seems to meet them, `lxc-checkconfig` returns all the things are enabled, just some were not loaded.
My problem was that after deleting that container I got an empty app:
![Zrzut_ekranu_20220820_001](https://user-images.githubusercontent.com/28653965/185755357-0ee8a832-62e7-49a7-b831-123076afaaa4.png)
But thank you for help, `lxc-destroy` returned no errors and app got fixed immediately, no restart even needed. I will try to install again, if all will work I will close this bug.

**Comment by Kabouik** [comment]
This sounds like daemon.py is not running. Can you show the output of `ps aux | grep daemon.py` before and after opening `harbour-containers`?

**Comment by JacekJagosz** [comment]
It now works, after deleting broken container on the terminal.
I managed to install Debian Bullseye with desktop just fine.
Not sure what caused a problem before, the terminal asking me for password never launched. Maybe setup didn't work with Buster and works woth Bullseye, maybe didn't like spaces in container names, or it was a random mistake.
Thank you for your help, and an awesome app!

**Comment by Kabouik** [comment]
Awesome!

**Comment by Kabouik** [comment]
Awesome!

You may have been in the case [described in the paragraph here](https://github.com/sailfish-containers/harbour-containers#how-to-use) the first time? Please let me know if yes.

**Comment by JacekJagosz** [comment]
> Awesome!
> 
> You may have been in the case [described in the paragraph here](https://github.com/sailfish-containers/harbour-containers#how-to-use) the first time? Please let me know if yes.

Yes, I was. I read this before installing, but I decided to delete it instead and try again. And this caused this to fail. Should have followed the steps...
